version: '2'
services:

  mysql:
      image: mysql:5.5
      environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: reservation
      ports:
        - 3307:3306
      volumes:
        - ./docker/mysql/sql:/docker-entrypoint-initdb.d
      command: mysqld --sql_mode=""
